// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssvlrahpbaeskxqkqnui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdmxyYWhwYmFlc2t4cWtxbnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjQ1NjgsImV4cCI6MjA2MTQ0MDU2OH0.87gyIcfQSEGo3vMdXyLeQ2H8i4ctPjCdglfF5D-hkv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);